### ISSUE TITLE
Issue with array type in POST/PUT form with v2

### ISSUE THREAD

**Issue by krishna5803** [dsternlicht/RESTool#100]
I was able to configure an array with below snippet in old version (Angular):

```
          {
              "name": "types",
              "label": "Types","arrayType":"select",
              "options": ["Type1", "Type2"],
              "type": "array", "required" : true
            }
```
it shows list of drop downs and constructs an array for POST/PUT.

This is not working in the new version.
As per doc, arrayType only accepts 'object' and 'text'. I tried with 'object' but it is not working.

**Comment by dsternlicht** [comment]
@krishna5803 did you try `"arrayType":"text"`?

**Comment by krishna5803** [comment]
yes. text is working. However, I am looking for a dropdown

**Comment by dsternlicht** [comment]
Try:
```
{
              "name": "types",
              "label": "Types",
               "arrayType":"text",
              "options": ["Type1", "Type2"],
              "type": "select", 
              "required" : true
}
```

**Comment by krishna5803** [comment]
As type is select, it's showing a single dropdown.

**Comment by dsternlicht** [comment]
@krishna5803 so I'm not sure what you're trying to accomplish. I thought you meant rendering a select box with pre-defined options.

**Comment by krishna5803** [comment]
I have an array property in the POST payload. And the values are fixed set. Hence, the below snippet adds dropdown with + icon. clicking on + icon adds one more drop down.  But the new version shows a big text area with placeholder (Enter json array).

{
              "name": "types",
              "label": "Types","arrayType":"select",
              "options": ["Type1", "Type2"],
              "type": "array", "required" : true
            }

**Comment by dsternlicht** [comment]
It's because the "arrayType" should be "text".

**Comment by dsternlicht** [comment]
> It's because the "arrayType" should be "text".

Closing the issue as I assuming that was the fix.
