### ISSUE TITLE
(Documentation) How authentication is supposed to work

### ISSUE THREAD

**Issue by sammyrulez** [dsternlicht/RESTool#105]
It would be awesome if the docs included a section on how to pass the current user back and forth to the rest APIs. Passing headers is well documented but it is unclear how to put values in there.

Thanks

**Comment by dsternlicht** [comment]
@sammyrulez that's a great input. I plan to add the option of setting headers dynamically (in config.js files), once it will be live, I'll add the relevant docs.

**Comment by dsternlicht** [comment]
@sammyrulez dynamic config is now available! (https://github.com/dsternlicht/RESTool/pull/98).
You may add logic there for authentication.
