### ISSUE TITLE
Navigation with argument & fetching with argument

### ISSUE THREAD

**Issue by ClementRoyer** [dsternlicht/RESTool#108]
# Issue

I haven't found a way to navigate through my object in an other page like : 

```
{{root}}/project/{id}/users
```

I thought I could achieve this by adding queryParams, so here is what I tried : 

## test

```
"url": "project/:projectID/users"
[...]
"queryParams": [
    {
        "name": "projectID",
        "value": 10,
        "label": "Project ID"
    }
]
```

## result

RESTool generate : 

```
/project/:projectID/users?projectID=10
```

## Solution proposition

A simple workaround for this issue could be that when you insert "projectID=10" in the url, to firstly look in the URL if it contains ":projectID" then replace it.

**Comment by ClementRoyer** [comment]
Tried to look in the code to implement this myself, but since you never use "url" and "queryParams" in the same time, and use "push" to add queryParams to url, I couldn't find a way to implement it.

Please note that I don't have any knwoledge on react js. Hope you can find a way to implement this.

**Comment by ClementRoyer** [comment]
Finally solved this issue by adding : to **http.service.ts** at line **70**

```
if (url.includes(":"+param.name))
    outputUrl = url.replace(":"+param.name, param.value);
else
    params.push(`${param.name}=${param.value || ''}`);
```

**Comment by dsternlicht** [comment]
@ClementRoyer we should add more docs about this.

**Comment by rutabagaman** [comment]
@dsternlicht Yes, please document this!  I just migrated from RESTool 1 which would do this substitution automatically, and I had to track town this bug with the source line number to discover the urlReplaceOnly parameter which can be used to get the old behavior back.

For anyone else who stumbles across this, just add urlReplaceOnly like so:

  "getAll": {
    "label": "Get All For Org",
    "url": "/subscriptions/:orgKeySearch",
    "dataPath": null,
    "queryParams": [
      {
        "name": "orgKeySearch",
        "value": "",
        "label": "Organization Search",
        "urlReplaceOnly": true
      }
    ],
    ...
