### ISSUE TITLE
Dropdown values are partially hidden

### ISSUE THREAD

**Issue by sorvis** [dsternlicht/RESTool#11]
Hello,

I'm seeing that dropdowns are partially hidden. Is this something I setup wrong or is this happening for others as well?

Thank you 

![image](https://user-images.githubusercontent.com/1037467/48776006-a7426600-ec9c-11e8-8ec3-975d8f954433.png)

**Comment by dsternlicht** [comment]
It's unusual. Which browser are you using?

**Comment by sorvis** [comment]
It seems to be happening everywhere I try. Below are Chrome, Firefox and IE:
![image](https://user-images.githubusercontent.com/1037467/48842919-93156c00-ed63-11e8-8eb4-4c1dcdafdfbb.png)

**Comment by dsternlicht** [comment]
Should be fix:
https://github.com/dsternlicht/RESTool/commit/f30c5525b8b9c1da5ef15415dc58b12a27ac0451

**Comment by sorvis** [comment]
Hello, sorry for the long delay. I was just now able to test the change, but it appears to still be having the issue.
