### ISSUE TITLE
Could not find config file

### ISSUE THREAD

**Issue by maelstrom9** [dsternlicht/RESTool#110]
I am getting "could not find config file" message in the browser.

I have followed these steps:

Clone RESTool repository to get started.

git clone https://github.com/dsternlicht/RESTool.git
cd RESTool
Install project dependencies by running:

npm i
We used React for developing this awesome tool so no need to install anything globally.

In order to start developing:

Start the development server by running npm start.
Browse to http://localhost:3000/.
The app will automatically reload on changes.

**Comment by maelstrom9** [comment]
Tried changing name of config-sample.json to config.json as well.

**Comment by dsternlicht** [comment]
@maelstrom9 Did you get along?

**Comment by maelstrom9** [comment]
Yeah, I have placed the config.json in the public folder as well. That seems to be working. Thanks!!

**Comment by dyze** [comment]
@maelstrom9 Thank you a lot for the solution you posted. I didn't know I had to manipulate files in public folder.
@dsternlicht Is it explained somewhere in your documentation (https://github.com/dsternlicht/RESTool)? It could help a lot newbies like me. By the way, your tool is great! thank you

**Comment by dsternlicht** [comment]
@dyze actually it is! :)
https://github.com/dsternlicht/RESTool#configuration

And thanks for the feedback!
