### ISSUE TITLE
Error parsing configuration at ".pages[0].methods.getAll.fields[0].type": should be equal to one of the allowed values

### ISSUE THREAD

**Issue by rentasad** [dsternlicht/RESTool#130]
Error parsing configuration at ".pages[0].methods.getAll.fields[0].type": should be equal to one of the allowed values index.js:1
    e index.js:1
    validateConfig config.service.ts:60
    App app.tsx:100
    React 6
    unstable_runWithPriority scheduler.development.js:697
    React 4
    unstable_runWithPriority scheduler.development.js:697
    React 5

Here is my config.js to recheck - I don't find the error on a type field. 
All my type fields are "text" except the id field, this is "integer". 
The display type is "table" - other "types" I don't found in the config file?
[config.js.txt](https://github.com/dsternlicht/RESTool/files/4657404/config.js.txt)

    loadConfig app.tsx:63

**Comment by dsternlicht** [comment]
@rentasad well, `integer` is actually not a valid type for the `getAll` fields. Simply use `text` as it will be rendered as text anyway :)
