### ISSUE TITLE
'object' fields are not being rendered if dataPath is set in config.json

### ISSUE THREAD

**Issue by s4ke** [dsternlicht/RESTool#142]
I have a put config like this:

```
"put": {
          "url": "<some_url>",
          "includeOriginalFields": true,
          "fields": [
            {
              "name": "payload",
              "type": "object",
              "label": "payload",
              "dataPath": "payload"
            }
          ]
        },
```

The object coming from the REST api looks like this:

```json
{
    "external_id": "str",
    "payload": {
         "payload": <some json here>
    }
}
```

This is the resulting form:

![image](https://user-images.githubusercontent.com/719760/87675544-cba75c00-c777-11ea-8729-91cb6884b76c.png)

When I remove the dataPath it works, but obviously displays the wrong data.

**Comment by dsternlicht** [comment]
@s4ke in your case you need to have both `payload` as name and dataPath.

What do you get when you try to add dataPath as well?

**Comment by s4ke** [comment]
I have `payload` already as dataPath. This seems to be a bug as this (hacky) code seems to work:

![image](https://user-images.githubusercontent.com/719760/87676350-ca2a6380-c778-11ea-8539-710b0d25f76c.png)

**Comment by dsternlicht** [comment]
So it **does** work?

**Comment by s4ke** [comment]
No, sorry for phrasing this badly. The original code:

![image](https://user-images.githubusercontent.com/719760/87676568-0bbb0e80-c779-11ea-904e-b5b5544e4ba2.png)

tries to look up the data in finalRawData by using the key, but key is overridden:

```
      if (field.dataPath) {
        key = `${field.dataPath}.${field.name}`;
      }
```
if we use dataPath.

**Comment by dsternlicht** [comment]
Can you fix and PR?

**Comment by s4ke** [comment]
I will try to figure something out and let you know :).

**Comment by s4ke** [comment]
@dsternlicht you have a pr.
