### ISSUE TITLE
Add support for object and array fields to be rendered in the list view

### ISSUE THREAD

**Issue by s4ke** [dsternlicht/RESTool#145]
The current implementation does not allow for rendering of objects and arrays in the card or table view for list endpoints. Is this something that we can add?

**Comment by dsternlicht** [comment]
Yes, of course.

**Comment by s4ke** [comment]
Okay, just checking (and creating a work item).

I will do the changes and add a PR.

**Comment by dsternlicht** [comment]
@s4ke any news? if not, may I close this issue?

**Comment by s4ke** [comment]
I have not come around to do it. If you want to close this for triaging, please feel free to close it.

**Comment by RyanPrice-King** [comment]
I have this issue too and have created a PR fix for it #199 :)

**Comment by dsternlicht** [comment]
@RyanPrice-King you're awesome!
