### ISSUE TITLE
Error parsing configuration at ".pages[0]": should NOT have additional properties

### ISSUE THREAD

**Issue by nirbr** [dsternlicht/RESTool#147]
I have setup a simple Spring Boot application that is meant for tracking bank transactions
I have a REST endpoint to get all transactions
I have setup config.json to call this endpoint on getAll method
but I get this error:
Error parsing configuration at ".pages[0]": should NOT have additional properties

![Screen Shot 2020-08-07 at 23 01 37](https://user-images.githubusercontent.com/44947807/89703560-a1028a80-d954-11ea-950b-c2ea3b4ae5b2.jpg)

it looks like the REST call is failing when I run through RESTool
although, I see the request hit the server and complete normally

this is my config file:

```
{
  "name": "Home Finance",
  "baseUrl": "http://localhost:8080",
  "pages": [
    {
      "default": true,
      "name": "Transactions",
      "id": "transactions",
      "description": "Transactions list",
      "methods": {
        "getAll": {
          "label": "Get Transactions",
          "url": "/transactions",
          "dataPath": null,
          "display": {
            "type": "table",
            "fields": [
              {
                "name": "id",
                "type": "text",
                "label": "id"
              },
              {
                "name": "accountId",
                "type": "text",
                "label": "accountId"
              },
              {
                "name": "description",
                "type": "text",
                "label": "description"
              },
              {
                "name": "date",
                "type": "text",
                "label": "date"
              },
              {
                "name": "amount",
                "type": "text",
                "label": "amount"
              }
            ]
          }
        }
      }
    }
  ]
}

```

This is the output when executing the REST call from postman:
![Screen Shot 2020-08-08 at 08 49 20](https://user-images.githubusercontent.com/44947807/89703641-36058380-d955-11ea-905a-32a748328cda.jpg)

Am I missing something?
Is this some configuration issue on my end or an issue in RESTool?

Thanks
Nir

**Comment by dsternlicht** [comment]
hey @nirbr, see the `config.schema` for a reference. Looks like the `label` property is irrelevant.
https://github.com/dsternlicht/RESTool/blob/master/src/assets/schemas/config.schema.json

**Comment by nirbr** [comment]
Hey Daniel,

I removed the label property from my config
but still the same issue
I tried removing it from the display fields and from "getAll"
didn't make a difference

Did you notice the in my screenshot that the REST call to the transactions resource on the server is RED?
It seems like the request gets out but no response
even though I can see that the request does get to the server and completes normally

![Screen Shot 2020-08-10 at 22 38 12](https://user-images.githubusercontent.com/44947807/89823569-5ce0d700-db5a-11ea-876e-50f650a17ac2.jpg)

**Comment by dsternlicht** [comment]
That's very weird, but both look like two different issues. For the request error - please check in the console that you don't have any CORS issues.

As for the config error, please go through the `config.schema`, and understand which field is causing that error.
https://github.com/dsternlicht/RESTool/blob/master/src/assets/schemas/config.schema.json

**Comment by nirbr** [comment]
Thanks. I got it working 
These were indeed 2 separate issues as you pointed out.

As a backend developer I wasn't aware of the CORS notion (might be a good idea to mention this in the docs)
For now I added this annotation on my controller and it solved the issue
@CrossOrigin(origins = "*", allowedHeaders = "*")
It's good enough for the development phase where I'm running everything locally
although I still don't understand why this happens since both my FE & BE are running on the same domain => localhost
Any references that can explain this?

The parsing issue was a problem in my config.json that didn't follow to the schema
I had put the "fields" within the "display" object
while they should be separate objects
This configuration file works

```
{
  "name": "Home Finance",
  "baseUrl": "http://localhost:8080",
  "pages": [
    {
      "name": "Transactions",
      "id": "transactions",
      "description": "Transactions list",
      "methods": {
        "getAll": {
          "label": "Get All",
          "url": "/transactions",
          "dataPath": "",
          "display": {
            "type": "table"
          },
          "fields": [
            {
              "name": "id",
              "type": "text",
              "label": "id"
            },
            {
              "name": "accountId",
              "type": "text",
              "label": "accountId"
            },
            {
              "name": "description",
              "type": "text",
              "label": "description"
            },
            {
              "name": "date",
              "type": "text",
              "label": "date"
            },
            {
              "name": "amount",
              "type": "text",
              "label": "amount"
            }
          ]
        }
      }
    }
  ]
}

```

**Comment by dsternlicht** [comment]
@nirbr Thanks for the update!
Regarding the CORS issue, if you're loading RESTool with the CDN method, that might be the issue since the script is being loaded from a different domain (unpkg.com). 

If that's an issue, you might consider using the `build` folder instead, and deploy it to your servers:
https://github.com/dsternlicht/RESTool#deploy

**Comment by dsternlicht** [comment]
Closing the issue for now.
