### ISSUE TITLE
set queryParams in POST method

### ISSUE THREAD

**Issue by daniel-at-sovos** [dsternlicht/RESTool#154]
I'm trying to implemente this API https://apidocs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/environments/%7Benv_name%7D/resourcefiles-0

Which requires query params in a POST method.
I tried adding "queryParams" to "post" but it seems to be ignored.

Anyone?

**Comment by dsternlicht** [comment]
Are these `queryParams` dynamic?

**Comment by daniel-at-sovos** [comment]
> Are these `queryParams` dynamic?

When I click on "Add Item" button, I could configure the form with the 3 required fields:

```
"post": {
                    "url": "/v1/organizations/my_company/environments/my_env/resourcefiles",                    
                    "fields": [
                        {
                            "name": "name",
                            "label": "Name",
                            "type": "text"
                        },
                        {
                            "name": "type",
                            "label": "Type",
                            "type": "select",
                            "options": [
                                "jsc",
                                "java",
                                "py",
                                "node",
                                "wsdl",
                                "xsd",
                                "xsl"
                            ]
                        },
                        {
                            "name": "file",
                            "label": "File",
                            "type": "file"
                        }
                    ]
                }
```
When I click on submit I get a "fail to fetch" error.

In the console tab I see this error: 
![image](https://user-images.githubusercontent.com/58528796/95205978-7e59ea00-07bc-11eb-9114-41bd4d53d163.png)

And in the Network tab I see the request is trying to add all three fields as form-data
![image](https://user-images.githubusercontent.com/58528796/95205871-59fe0d80-07bc-11eb-8be2-c93b23cfba49.png)

This is a working example (params **name** and **type** as queryString and **file** as form-data): 
![image](https://user-images.githubusercontent.com/58528796/95206141-b5300000-07bc-11eb-9d1c-11adcd0cd128.png)

**Comment by dsternlicht** [comment]
You need to enabled CORS in the backend. Please read more here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by daniel-at-sovos** [comment]
> You need to enabled CORS in the backend. Please read more here:
> https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

This is a cloud API owned by Google!

Although there's a CORS error in the console tab, in the network tab there are two requests, the 1st one shows the cors request happened successfully: 
![image](https://user-images.githubusercontent.com/58528796/95809807-091f7500-0ce6-11eb-81cb-076af9a1778e.png)

And the second request is the actual one, but trying to pass all three params in the body as form-data 
![image](https://user-images.githubusercontent.com/58528796/95810026-6ca9a280-0ce6-11eb-9998-e1cd7269fa3a.png)

The goal here is passing only one param in the body as form-data (file) and the other two (name & type) as query param

**Comment by dsternlicht** [comment]
Got it.
On that case, you need to add to the name & type fields the `useInUrl` property.

See here:
https://github.com/dsternlicht/RESTool#input-fields

**Comment by daniel-at-sovos** [comment]
I added like this.. didn't seem to work (same result as before) 
![image](https://user-images.githubusercontent.com/58528796/96061255-2761ae00-0e69-11eb-8881-4170933fd879.png)

I searched the whole project for usages of `useInUrl` but it doesn't seem to be used: 
![image](https://user-images.githubusercontent.com/58528796/96061309-47916d00-0e69-11eb-887f-38bdd8ff3427.png)

**Comment by daniel-at-sovos** [comment]
This is how I solved https://github.com/dsternlicht/RESTool/pull/156 (also for issue #155 )
