### ISSUE TITLE
Reading a plain text returned in the body for a getSingle method

### ISSUE THREAD

**Issue by daniel-at-sovos** [dsternlicht/RESTool#155]
I'm implementing some Google's Apigee API (https://apidocs.apigee.com/management/apis/get/organizations/%7Borg_name%7D/environments/%7Benv_name%7D/resourcefiles/%7Bresource_type%7D/%7Bresource_name%7D) and this one does't return a JSON in the body (instead just returns the plain text in the body).

how can I get this content to display in the pop up for getSingle and put methods? Should I use dataPath (any wild card since it's not a json)?

**Comment by dsternlicht** [comment]
Well, at the moment RESTool doesn't support plain text.
Feel free to create a PR to support it!
