### ISSUE TITLE
Using config.js

### ISSUE THREAD

**Issue by kunalnhes** [dsternlicht/RESTool#158]
Using dynamic config.js throws me the error config.js not found error during development. Not sure what's the issue. Can someone help with it.

**Comment by dsternlicht** [comment]
@kunalnhes where did you put the config.js file? in the `public` folder?

**Comment by kunalnhes** [comment]
yes. Similar to what I did for config.json Config.json works fine for me.

**Comment by EoinGriffin-AI** [comment]
I'm getting a similar error.
For me it's returning a 404 for config.json, but it doesn't even attempt to load config.js

![image](https://user-images.githubusercontent.com/6333375/102572602-68f91a00-40a1-11eb-9014-a48b4655c1cb.png)

**Comment by dsternlicht** [comment]
Can you try to run it locally in dev mode and see if this issue still appear?

**Comment by tkskumar** [comment]
is there any way to pass dynamic value of token in header 
requestHeaders or take input from UI for this field
@dsternlicht

**Comment by dsternlicht** [comment]
@tkskumar you may use a dynamic config file (`config.js`) and attach headers dynamically to requests.

**Comment by mato848** [comment]
I experience the same issue with config.js
Getting error:
`index.js:1 Could not load config file TypeError: Failed to fetch dynamically imported module: http://localhost:3000/static/js/config.js`

**Comment by dsternlicht** [comment]
@mato848 Where did you put it? on which folder?

**Comment by mato848** [comment]
I have just renamed the `public/config-sample.js`
Here are steps to reproduce it:
```
git clone git@github.com:dsternlicht/RESTool.git
cd RESTool
mv public/config-sample.js public/config.js
npm i
npm start
```

**Comment by dsternlicht** [comment]
Can you try to put it in the `src` folder?

**Comment by mato848** [comment]
Putting it into 'src' folder did not work, but putting it into `public/static/js/config.js` did the trick :)

**Comment by dsternlicht** [comment]
Lol 🙂

Good to know.
