### ISSUE TITLE
"dataTransform" missing for "getSingle", "put", "post"

### ISSUE THREAD

**Issue by EoinGriffin-AI** [dsternlicht/RESTool#160]
Hi,
Is it possible to implement a "dataTransform" function for the "getSingle" method?
As it is right now I need to make changes to my server's API to make this work, when it would be preferable to avoid that.
The problem is that the data structure when sending a POST or PUT is different from the data structure that gets returned from a GET call. (that's not ideal, and not the fault of RESTool of course. I'm just hoping a "dataTransform" method would be relatively simple to implement, since it was added for "getAll")

Alternatively (or additionally?) if we had a "dataTransform" property on the POST and PUT methods to transform outgoing data, that would be another way to solve the problem.

Let me know if that is unclear.

Thank you,
Eoin

(I'm going to look into what would be required for me to submit a PR to this repo for this change, but in the meantime I would love to hear your feedback to this request. Thanks!)

**Comment by EoinGriffin-AI** [comment]
I just added a PR for this functionality.
https://github.com/dsternlicht/RESTool/pull/162

**Comment by dsternlicht** [comment]
@EoinGriffin-AI Sweet. 

Approved & merged. Are you planning to add it to `post` and `put` methods as well?

**Comment by EoinGriffin-AI** [comment]
@dsternlicht Thanks :-)
No, I think this is enough for now. The other issue I created (unable to select multiple options from a `select`) is a blocker for me. Until there's a solution for that I don't think we can use this new, rewritten version of RESTool.

**Comment by dsternlicht** [comment]
Got it. So I'm closing this issue for now.
