### ISSUE TITLE
Is it possible to display nested JSON?

### ISSUE THREAD

**Issue by dineshkr3** [dsternlicht/RESTool#163]
Hello,
I am exploring RESTool to use in my project and so far I found it really impressive.

I wanted to check if following scenario is possible
{
  "name": "string",
  "employeeId": "string",
  "address": {
    "firstLineOfAddress": "string",
    "secondLineOfAddress": "string",
    "area": "string",
    "State": "string"
    
  }
}
I want to display above in UI and also build post request but did not find a type to display this nested JSON.
Is it even possible as of now?
Thanks

**Comment by dsternlicht** [comment]
Hey @dineshkr3!

Of course. Please read about the 'dataPath' property. This will allow you to work with nested objects.

**Comment by dineshkr3** [comment]
Thank you @dsternlicht 

Isnt dataPath used if I just want to show address ?
I want to show/Modify both parent and child like below.
`"post": {
          "url": "/partner-orgs",
          "fields": [
            {
              "name": "name",
              "type": "text",
              "label": "Organization Code"
            },
            {
              "name": "employeeId",
              "type": "text",
              "label": "Business Name"
            }
			{
              "name": "address",
              "type": "card",
              "label": "Address",
              "fields" : [
                {
                  "name": "firstLineOfAddress",
                  "type": "text",
                  "label": "First Line of Address"
                },
				{
                  "name": "secondLineOfAddress",
                  "type": "text",
                  "label": "First Line of Address"
                },
				{
                  "name": "area",
                  "type": "text",
                  "label": "Area"
                },
				{
                  "name": "State",
                  "type": "text",
                  "label": "State"
                }
              ]
            },
			]
		}`
So that I can add parent fields as well as child fields in one request

**Comment by dsternlicht** [comment]
@dineshkr3  Hmm well, you'll need to define both in the POST json object.
One with `dataPath` to the children, and the other one without it.
