### ISSUE TITLE
Moving Config.js to client-side

### ISSUE THREAD

**Issue by alessio-capello** [dsternlicht/RESTool#172]
Hi, i'm trying to move the config.js file on the client side since i'd like to load the strings inside it (like description and so on) from another file with the idea to develop a localization file. 
I have an issue when i try to import Config.js and then i set the remoteConfig variable (inside App.tsx) as the exported configuration. The config file works correctly when i use it in the regoular way.

Do you have any idea on how to solve this? 

Thanks

------------------------------
EDIT: i solved with a little workaround, the config file can be exported as a function so the arguments related to localization can be passed as parameters.

This issue can be closed

**Comment by dsternlicht** [comment]
@alessio-capello Sweet :)
