### ISSUE TITLE
Dynamic configuration computed on every request

### ISSUE THREAD

**Issue by lamaland** [dsternlicht/RESTool#182]
Hi there, I've been playing with dynamic configuration, but couldn't find a way to set request headers dynamically.

My use case is the following : every API request needs timestamps and other new dynamic values **on every request**. (computing these values only on loading configuration can't work so)

Do I miss something there?

Thanks!

```
const testFunction = () => ({dynamicValue : `test_${Math.random()}`})

export default {
  name: "...",
  favicon: "...",
  baseUrl: "...",
  pages: [
    {
      name: "Test",
      id: "test",
      description: "...",
      requestHeaders: testFunction
    }
  ]
}
```

**Comment by dsternlicht** [comment]
@lamaland You need to run the function. Try: `requestHeaders: testFunction()`.

**Comment by lamaland** [comment]
@dsternlicht, Thanks for your reply, but running the function doesn't make the value to be recomputed on every request.

**Comment by dsternlicht** [comment]
@lamaland good point. So I'm not sure at the moment RESTool supports running the function before every request.

**Comment by lamaland** [comment]
Yep, actually, exporting a module like this (evaluating the function) can't work for every request.
Looking at the restool initialization mechanism, the configuration is loaded on "app mount" inside a react effect, so it is never refreshed.
More logic would be needed here, for sure.
Maybe better to use another solution (library) for this specific use case.
Thanks for your time.
