### ISSUE TITLE
Disable Character not working

### ISSUE THREAD

**Issue by bikkimahato** [dsternlicht/RESTool#189]
Disable Character is not working for any character, it is giving 404 not found.
![image](https://user-images.githubusercontent.com/42492682/139574074-2b92e023-22a6-4470-9d23-7f5c9240e391.png)

**Comment by dsternlicht** [comment]
Hey @bikkimahato I'll need a bit more context :)
What's the use case? What are you trying to achieve?

**Comment by dsternlicht** [comment]
Closing the issue for now.
