### ISSUE TITLE
Action buttons in getAll pages wrap when there are long cells

### ISSUE THREAD

**Issue by jessemcdowell-AI** [dsternlicht/RESTool#19]
I have a page with a few columns, and some of them can have a bit of text. It causes the action buttons at the right to look a little funny. Here's a screenshot:

![image](https://user-images.githubusercontent.com/7407231/50936020-e8e0c900-1422-11e9-870e-768a9bf80e36.png)

**Comment by dsternlicht** [comment]
Fixed.
https://github.com/dsternlicht/RESTool/commit/b5c825aad5f68e279e755df6447db99ffcd5c05e
