### ISSUE TITLE
(feat request) multi select on type 'array'

### ISSUE THREAD

**Issue by msarsha** [dsternlicht/RESTool#2]
Hey !

Will be great if there was an option to add a drop down (with multiple select option) to the update form (post\put requests)

Similar to the `queryParams` `select` type.

For example, a Country that contain a list of Cities that the user can edit:

Given a Country object structure of:

```javascript
{
    name: "Spain",
    cities: [
        {
            cityName: "Madrid",
            cityId: "225"
        },
        {
            ciryName: "Barcelona",
            ciryId: "227"
        }
]
}
```

````typescript
{
    "name": "cities",
    "label": "Cities",
    "type": "select",
    "multi": "true",
    "selectType": "object",
    "selectLabel": "cityName", // path to the display label
    "selectValue": "cityId" // path to the value (all selected cities will be sent as an array of cityIds)
}
````

**Comment by dsternlicht** [comment]
We developed a very basic support for Array type data fields. We had an idea of adding special dynamic UI with add/remove actions to array items, but it was a bit complicated to achieve with Angular 2 forms.

Any help from the community would be appreciated! :)

**Comment by arnagarjun** [comment]
would love to see this feature..
will be very helpful

**Comment by dsternlicht** [comment]
Closing this issue, this feature has been added.
