### ISSUE TITLE
config.json is loaded multiple times when application loads

### ISSUE THREAD

**Issue by jessemcdowell-AI** [dsternlicht/RESTool#21]
If I look in the network tab of the chrome devtools, It seems that config.json is being loaded multiple times. I also see this behavior on the hosted sample app, so I don't think I introduced it, but I do seem to have made it worse.

I don't think it's causing an issue, but it may speed up application load time if it was prevented.

Here's what it looks like in my devtools:
![image](https://user-images.githubusercontent.com/7407231/50987942-d6689d00-14bf-11e9-96a5-b64e076ca7d0.png)

**Comment by dsternlicht** [comment]
That's interesting. 

@jessemcdowell-AI did you figure it out?

**Comment by jessemcdowell-AI** [comment]
TBH, I haven't looked at it at all.

**Comment by jessemcdowell-AI** [comment]
Should be fixed by #62
