### ISSUE TITLE
Adding DataTransform on CustomAction body

### ISSUE THREAD

**Issue by jphilippl** [dsternlicht/RESTool#210]
Hello,

I had a need for transforming the body of a custom action (in my case, to transform the content into a literal instead of key:values). I'd like to create a pull request for it, as per the changes I made here [https://github.com/jphilippl/RESTool/tree/feature/transform-custom-action](url).

Do you have any feedback before I go forward?

**Comment by dsternlicht** [comment]
@jphilippl sounds great. Have you opened a PR yet? I can't see it.

**Comment by jphilippl** [comment]
I have now created [https://github.com/dsternlicht/RESTool/pull/211](url)

**Comment by dsternlicht** [comment]
@jphilippl Overall - looks great. I've added a couple of comments.

**Comment by jphilippl** [comment]
@dsternlicht I have realized from your comments that I have branched from master but targeted the dev branch. I can either target master or branch from dev, let me know which works best for you.

**Comment by dsternlicht** [comment]
@jphilippl that's ok, I reviewed the code and compared it with `master`. All is merged now:
https://github.com/dsternlicht/RESTool/pull/212
