### ISSUE TITLE
Handling non-array Results

### ISSUE THREAD

**Issue by jphilippl** [dsternlicht/RESTool#214]
Hello.

Thanks @dsternlicht for merging in my earlier PR. I have made a new PR to push a modification that allows me to create RESTool pages for a greater variety of existing REST APIs I am dealing with.

https://github.com/dsternlicht/RESTool/pull/213

Instead of returning an error when a response is not an array, I propose to make it an array of a single item. This allows pages to be created even for REST paths that return a single object. I find that RESTool scales down gracefully when displaying a single line or card on the page.

**Comment by dsternlicht** [comment]
Nice catch 🙂

Approved and merged.
