### ISSUE TITLE
RESTool 2.0 (demo) does not work

### ISSUE THREAD

**Issue by stroetmann-schattke** [dsternlicht/RESTool#246]
Error "Failed to fetch" on all pages of the online-demo.

https://dsternlicht.github.io/RESTool/

**Comment by dsternlicht** [comment]
Hey @stroetmann-schattke that's right, we had mocks server in Heroku but they are down since they removed support for free dynos.

But the tool is still up and working :)

**Comment by stroetmann-schattke** [comment]
Hi @dsternlicht thank you, I cloned your project and got the API running and the frontend, too! 😀👍
(But It did not work out of the box, I had to change the url from /employee to /employees and remove the dataPath.)
