### ISSUE TITLE
dataPath in create and update?

### ISSUE THREAD

**Issue by stroetmann-schattke** [dsternlicht/RESTool#247]
Hi,
would it be possible to get the dataPath working when creating / updating a record with post / put?

We use a third party API-Tool which needs everything be wrapped in a "data"-property.

I checked the code and think it could be done in page.comp.tsx / addItem / updateItem at JSON.stringify(body)?

**Comment by dsternlicht** [comment]
Hey @stroetmann-schattke, yes of course. See below:
https://github.com/dsternlicht/RESTool?tab=readme-ov-file#input-fields
