### ISSUE TITLE
UrlUtils.extractIdFieldName is not parsing placeholders correctly

### ISSUE THREAD

**Issue by katsanva** [dsternlicht/RESTool#34]
RegExp to extract id `/:([a-zA-Z0-9_-]+)[\/?#&]?.*/` takes API port as parameter:

`http://localhost:3000/admin/profiles/:_id` matches to `:3000/admin/profiles/:_id` which causes requests like `http://localhostundefined/admin/profiles/5c52b178475ecb6c52cf87fd`

**Comment by dsternlicht** [comment]
@jessemcdowell-AI 🤴🏻

https://github.com/dsternlicht/RESTool/pull/36
