### ISSUE TITLE
MainViewComponent.getRowData misses to bind headers for getSingle method

### ISSUE THREAD

**Issue by katsanva** [dsternlicht/RESTool#35]
`MainViewComponent.getRowData` misses to bind headers for `getSingle` method when `requestHeaders` is present in config for `getSingle` method.

**Comment by katsanva** [comment]
It seems that [this line](https://github.com/dsternlicht/RESTool/blob/master/src/app/components/main-view/main-view.component.ts#L93) should look like

```ts
    return actualMethod(getUrl, getMethod.requestHeaders);
```

**Comment by dsternlicht** [comment]
@katsanva Could you please a PR with the fix?
