### ISSUE TITLE
[question] Bundled purecss

### ISSUE THREAD

**Issue by katsanva** [dsternlicht/RESTool#40]
Is there any reason `purecss` is bundled in project?

I can see there are some style changes, but is that possible to leave only changed styles here in repo and treat `purecss` as dependency?

**Comment by dsternlicht** [comment]
The project uses `purecss` for the UI.

As for you question, I guess it's possible. Would you like to create a PR with the solution?

**Comment by katsanva** [comment]
I have tried to install `purecss` as npm dependency and replace bundled imports already. The project builds and runs successfully, but some styles are messed up. I will try to investigate a bit, but I would really appreciate if you can point me to some well-known changes in bundled `purecss`.

**Comment by katsanva** [comment]
@dsternlicht Thanks! By the way, I haven't rebuilt the bundled `dist`, so you can do it before closing this.

**Comment by dsternlicht** [comment]
@katsanva 👍
