### ISSUE TITLE
Add Scrolling Support For Pages Menu

### ISSUE THREAD

**Issue by sorvis** [dsternlicht/RESTool#42]
Hello,

The side bar on the left that holds the pages does not scroll when the bar is longer then the height of the browser. We have tested this in FireFox and in Chrome.

![image](https://user-images.githubusercontent.com/1037467/52285458-5b669b00-2934-11e9-820b-81688f6abc98.png)

Would this make sense to add as a feature?

Thank you

**Comment by dsternlicht** [comment]
Fixed :)
https://github.com/dsternlicht/RESTool/commit/f4a7b047127874dfb4b9dfb93397977af9dc0d3f

**Comment by sorvis** [comment]
@dsternlicht that did the trick. Thank you

**Comment by dsternlicht** [comment]
Sure :)
