### ISSUE TITLE
Support multipart/form-data requests with <input type="file">

### ISSUE THREAD

**Issue by DougSchmidt-AI** [dsternlicht/RESTool#44]
This may be the more generic version of the #6 feature request.

We have a few API operations which allow the upload of a file along with other request parameters. This is typically done as a `POST` request with `Content-Type: multipart/form-data` header.

Here's the approach I'll try to code up:
- Extend the [field-input](https://github.com/dsternlicht/RESTool/blob/master/src/app/components/input/field-input.component.html) component to support `type="file"`
- When composing the `data` object for a POST/PUT operation, check if any fields are `type="file"`
- If no `type="file"` form fields exist, continue composing the `data` object as a JSON document
- If one or more `type="file"` form fields exist, compose the `data` object as a [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) object
- For each non `type="file"` field, call `formData.append(fieldName, fieldValue)` to send the request parameter as a string value
- For each `type="file"` field, call ``formData.append(fieldName, field.fieldBlob, field.filename)``

**Comment by dsternlicht** [comment]
@DougSchmidt-AI That sounds like a plan :)

**Comment by dsternlicht** [comment]
Done by the one and only @DougSchmidt-AI 🥇 
https://github.com/dsternlicht/RESTool/pull/46
