### ISSUE TITLE
remoteUrl setting not working

### ISSUE THREAD

**Issue by drewbelmont** [dsternlicht/RESTool#5]
I'm trying to use the remoteUrl property, and it's not working.  At first the setting didn't seem to be read at all, based on what I was (not) seeing in the browser dev tools. I figured out the first problem, which is that the current files in the /dist folder don't seem to have the remoteUrl change.  So I did a new build with the latest /src.

That improved things.  Now I see that the url in my remoteUrl property is getting called, and is returning the right json response, but I'm getting a blank page -- the json does not seem to be used.

**Comment by dsternlicht** [comment]
Hey Drew,

Any chance you could add a sample of the json file you're trying to use?
