### ISSUE TITLE
dataPath parameter in getAll not returning anything

### ISSUE THREAD

**Issue by SonyaKaramchandani** [dsternlicht/RESTool#55]
Hello! I just started using the tool and I'm finding it extremely helpful, so thank you! :)

I'm not sure if this is a bug or just incorrect usage, but my parameters don't seem to be returning any data when trying to parse through a dataPath array. Using the app example:

``` 
"methods": {
        "getAll": {
          "label": "Get Contacts",
          "url": "http://restool-sample-app.herokuapp.com/api/contacts",
          "dataPath": "friends",
          "display": {
            "type": "table",
            "fields": [
              {
                "name": "name",
                "label": "Friend",
                "type": "text"
              },
            ]
          }
```

Given what I understand about the dataPath parameter from the README, I would expect to get the `friends` array from http://restool-sample-app.herokuapp.com/api/contacts returned as my data, with the field displaying the name of the field. Rather, nothing is being returned:
<img width="666" alt="2019-04-03_16-55-47" src="https://user-images.githubusercontent.com/35080007/55512644-a1d52f00-5631-11e9-899b-236b6736505d.png">

Any help would be appreciated. Thanks!

**Comment by jessemcdowell-AI** [comment]
That API returns data that looks like this:
````
[{
  "id": "454647789",
  "friends": [{"name":"Daniel", "id":12}],
  // ...
}, {
  // ...
}]
````

The data path at that level is meant for data that looks like this:
````
{
  "friends": [
    {"name":"Daniel", "id":12}
  ]
}
````

There isn't currently a way to show a single property from an array object, AFAIK.

**Comment by dsternlicht** [comment]
@jessemcdowell-AI actually, it's a bit inaccurate. The `dataPath` property in the `getAll` method refers to from where RESTool will try to get the entities array from.

Meaning, if the http request result looks like this:
`
{
   success: true,
   data: {
       friends: [...]
   }
}
`

Then the `dataPath` would be `data.friends`.

What @SonyaKaramchandani want is a dataPath for a specific field which currently as @jessemcdowell-AI said is not supported.

@SonyaKaramchandani You're more than welcome to add this feature and create PR for it! 😎

**Comment by SonyaKaramchandani** [comment]
Thanks @dsternlicht and @jessemcdowell-AI for clarifying! I figured as much. Would be nice though. 😛 

I guess the next best thing would be to create a separate endpoint for `friends` and extract the data from there. 

Maybe later down the road I will add this feature in myself. Thanks for all your help!
