### ISSUE TITLE
Intermittent errors loading first page, unable to get undefinedhttp://...

### ISSUE THREAD

**Issue by jessemcdowell-AI** [dsternlicht/RESTool#61]
After a recent update we started seeing intermittent 404 errors loading the first page in RESTool. I can't seem to reproduce it with the chrome debugger open, but I can seem to get it about 1 in 10 times by hitting the refresh button continuously.

It seems the tool is trying to load `undefinedhttp://...`

**Comment by jessemcdowell-AI** [comment]
I have done a little investigation into this. It seems to be caused by this line:
https://github.com/dsternlicht/RESTool/blob/3a012b113d14e95a0213116b2e0a1f4d2042d5dc/src/app/services/requests.service.ts#L33
executing before this line:
https://github.com/dsternlicht/RESTool/blob/3a012b113d14e95a0213116b2e0a1f4d2042d5dc/src/app/services/requests.service.ts#L26

I think this is another symptom of https://github.com/dsternlicht/RESTool/issues/21, which is now more noticeable because of https://github.com/dsternlicht/RESTool/pull/56.

Since I've already come this far, I'll take a crack at fixing both problems.

**Comment by dsternlicht** [comment]
Nice catch 🙏
