### ISSUE TITLE
bypass ssl check on the restAPI call

### ISSUE THREAD

**Issue by mlahegamine** [dsternlicht/RESTool#63]
Hello 
is there a way to bypass the ssl check on the RESTAPI call. the http client of RESTool is rejecting the tls handshake due to my server self signed cert.

thanks for you help

**Comment by jessemcdowell-AI** [comment]
This is a browser security feature, so it's not really something that can be disabled from within RESTool. There are a few things that may make it better though, but it depends on what you're trying to do.

If this is just for a local test environment, you can install that root certificate associated with your self-signed key on the computer you're running the browser on. It's possible to make the browser accept the HTTPS handshake this way. There are other steps you may need to take, you should be able to find instructions on the internet.

If you want this to work for other people, you can trying putting RESTool directly on the server where the API is. Then a user would be able to approve the lower security before the API is hit, so the API calls should go through.

**Comment by mlahegamine** [comment]
thanks for your response, now i'm using a certificate signed by a public CA and i have no more issues with TLS

**Comment by dsternlicht** [comment]
@mlahegamine Great. Closing the issue.
