### ISSUE TITLE
How to handle pagination?

### ISSUE THREAD

**Issue by mkjsix** [dsternlicht/RESTool#65]
Hi,

I have lots of sample data, my API handles pagination natively using the "pagesize" and "page" query parameters: does RESTool handles pagination somehow? I was thinking about "previous" and "next" buttons, or something like that.

BTW, we have created a tool which makes super-easy to create API backends (see https://restheart.org), we are testing it with RESTool.

**Comment by dsternlicht** [comment]
@mkjsix this is so cool!

As for your request, I added a task to RESTool’s backlog to support pagination, but meanwhile, you may use the ‘queryParams’ fields on order to set the pagination Paramus in the url.

**Comment by dsternlicht** [comment]
Just for a reference:
https://github.com/dsternlicht/RESTool/projects/1#card-22208147

**Comment by Thomas-Pamono** [comment]
I second that request. Would be major useful!

**Comment by dsternlicht** [comment]
I didn't forget you! :)

**Comment by laudibert** [comment]
@dsternlicht do you have anything in mind for the way the configuration would be done for this feature ? I ask because I would like to try and work on a PR for this.

Also, what do you think about giving pagination two types, the "classic" way and using infinite scroll ?

**Comment by dsternlicht** [comment]
@laudibert sounds amazing!

Regarding how to configure this up, I would go on a new property `pagination` in the `getAll` method config.

There are a few ways that developers support pagination, but maybe we could start with the most simple way - query params.

So maybe the `pagination` property will look as follow:

```
pagination: {
     type: "query", // Could also be "headers" in the future
     params: {
          limit: {
                name: "limit", // value is the name of the query param
                value: "10", // default value
          },
          page:  {
                name: "page", // value is the name of the query param
                value: "1", // default value
          },
          totalResults:  {
                name: "total", // value is the name of the query param
                value: "0", // default value
          },
          totalPages:  {
                name: "pages", // value is the name of the query param 
                value: "0", // default value
          },
          sortBy:  {
                name: "sort", // value is the name of the query param 
                value: "created", // default value
          },
          descending:  {
                name: "desc", // value is the name of the query param 
                value: "true", // default value
          },
     }
}
```

WDYT?

**Comment by laudibert** [comment]
@dsternlicht great, thank you!

`totalPages` and `totalResults` seem redundant though. Through `totalResults` and `limit` you can determine `totalPages`, it would gives less room for incoherent data. And in that case `totalResults` could be named `total` or `count`? What do you think?

**Comment by laudibert** [comment]
Also, shouldn't the default value of `sortBy` be something like the first defined field in the `fields`array rather than a static value?

**Comment by dsternlicht** [comment]
> @dsternlicht great, thank you!
> 
> 
> 
> `totalPages` and `totalResults` seem redundant though. Through `totalResults` and `limit` you can determine `totalPages`, it would gives less room for incoherent data to only have `totalResults`. And in that case, it could be named `total` or `count`? 
> 
> 
> 
> What do you think?

Sound reasonable 🙂

**Comment by dsternlicht** [comment]
> Also, shouldn't the default value of `sortBy` be something like the first defined field in the `fields`array rather than a static value?

Maybe there shouldn’t be a default behavior at all. The api will probably sort the items as he wants.

**Comment by laudibert** [comment]
In the configuration format we talked about, two things are mixed: parameters to send to API to handle pagination and information returned from the API that is useful for pagination. For example `limit` is a parameter while `total` is just information returned from the API. 

The model would be something like this then: 

```
export interface IConfigPagination {
  source: 'query' // TODO: add 'headers'
  type: 'lazy-loading' // TODO: add 'buttons'
  params: IConfigPaginationParams
  fields: IConfigPaginationFields
}

export interface IConfigPaginationParams {
  page: IQueryParamConfig
  limit?: IQueryParamConfig
  sortBy?: IQueryParamConfig
  descending?: IQueryParamConfig
}

export interface IConfigPaginationFields {
  page?: {
    dataPath: string,
    display: boolean,
  },
  total?: {
    dataPath: string,
    display: boolean,
  },
}

export interface IQueryParamConfig {
  name: string
  value?: string
  urlReplaceOnly?: boolean
}


export interface IQueryParam extends IQueryParamConfig {
  value: string
}

```

What do you think @dsternlicht ?

**Comment by dsternlicht** [comment]
> In the configuration format we talked about, two things are mixed: parameters to send to API to handle pagination and information returned from the API that is useful for pagination. For example `limit` is a parameter while `total` is just information returned from the API.
> 
> The model would be something like this then:
> 
> ```
> export interface IConfigPagination {
>   source: 'query' // TODO: add 'headers'
>   type: 'lazy-loading' // TODO: add 'buttons'
>   params: IConfigPaginationParams
>   fields: IConfigPaginationFields
> }
> 
> export interface IConfigPaginationParams {
>   page: IQueryParamConfig
>   limit?: IQueryParamConfig
>   sortBy?: IQueryParamConfig
>   descending?: IQueryParamConfig
> }
> 
> export interface IConfigPaginationFields {
>   page?: {
>     dataPath: string,
>     display: boolean,
>   },
>   total?: {
>     dataPath: string,
>     display: boolean,
>   },
> }
> 
> export interface IQueryParamConfig {
>   name: string
>   value?: string
>   urlReplaceOnly?: boolean
> }
> 
> 
> export interface IQueryParam extends IQueryParamConfig {
>   value: string
> }
> ```
> 
> What do you think @dsternlicht ?

Looks great.

**Comment by dsternlicht** [comment]
Added in https://github.com/dsternlicht/RESTool/pull/120
