### ISSUE TITLE
(feature request) use variables/js methods pointers in the config.json

### ISSUE THREAD

**Issue by Stacrux-amadeus** [dsternlicht/RESTool#68]
After discussing with Daniel I open this issue request :)

I would like to automatically set the header at each call.
My use case is the following:
In my company the auth header is generated at each call by a function that takes a static password and manipulates it (salt + some encoding).

For instance, in Postman this is evaluated every time in the pre-request scripts (which I have access to) and plugged in the header of the request, I would like to have a similar behavior.

The best option for me would be to just copy paste this js method somewhere and plug it in the config.json, than when I hit the submit/get button the js executed and the header is filled accordingly. (or to adopt a similar strategy, I am fine with anything)

Thanks!

**Comment by dsternlicht** [comment]
Done!
PR reference: https://github.com/dsternlicht/RESTool/pull/98
