### ISSUE TITLE
?queryvariable=xxx to ?queryvariable=like=xxx

### ISSUE THREAD

**Issue by vamshimohank** [dsternlicht/RESTool#7]
Hi,

First of all thanks for writing a very easy too use UI. I have question regarding slight modification in the code. As I am very new to typescript (I am assuming the .ts files are so called), this might be a dumb question. 

So, the item name in queryParams is appended to the url with a prefix '?' and suffix '='. I will like to modify the suffix to '=like=' or something else. I guess its a straightforward thing. 

Could you please guide me where I should be changing in the code to obtain this feature. 

Thanks and regards
Vamshi

**Comment by dsternlicht** [comment]
Hey Vamshi,

I think that what you're looking for is under the buildUrl method:
https://github.com/dsternlicht/RESTool/blob/master/src/app/services/requests.service.ts#L70
