### ISSUE TITLE
404 issues? (No Idea what I'm doing)

### ISSUE THREAD

**Issue by MayhemBill** [dsternlicht/RESTool#72]
I'm trying to make a rest api to hold json info, however testing out the dist folder of your git I get 404 errors on the site, I feel I am doing something wrong, but I am not sure.

I should specify that I am getting 404 when accessing the API

**Comment by dsternlicht** [comment]
Hey! Could you add a bit more info? Maybe some screenshots? Code snippet? Anything would be helpful :)

**Comment by MayhemBill** [comment]
Ah my issue is that this isn't an API of itself, but a front end for an API.

**Comment by dsternlicht** [comment]
Hmmm I’m sure I understand...

**Comment by MayhemBill** [comment]
This itself isn't a REST API, but more of a front end for managing a REST API

**Comment by dsternlicht** [comment]
So what’s your use of RESTool?
