### ISSUE TITLE
(Feature Request) JSON schema for config.json

### ISSUE THREAD

**Issue by hikaru150s** [dsternlicht/RESTool#73]
It might be good to create a schema for `config.json` so user could easily create and validate their config.

**Comment by dsternlicht** [comment]
Sounds like a great idea. 
BTW, I'm also planning to create another UI tool that generates the `config.json` file for RESTool so it would be easier to create and edit it.

**Comment by hikaru150s** [comment]
How about combining lowdb with UUID/GUID?
If you planning to use a web version of UI tool then you may want to try lowdb with some UUID/GUID to differ each JSON DB.

**Comment by dsternlicht** [comment]
Solved with #118
