### ISSUE TITLE
send queryParam request before returning getAll

### ISSUE THREAD

**Issue by SonyaKaramchandani** [dsternlicht/RESTool#74]
One of my endpoints I'm trying to configure with RESTool have the following structure:

`/Countries/:countryId/cities` by which a list of cities and their properties are returned after specifying the countryId. 

```
"methods": {
        "getAll": {
          "label": "Get city properties for countries",
          "url": "/Countries/:countryId/cities",
          "queryParams": [
            {
            "name": "countryId",
            "label": "Country",
            "type": "select",
            "optionSource": {
              "url": "/Countries/",
              "displayPath": "country",
              "valuePath": "countryId"
            }
```

From my understanding, a `queryParam` object should appear asking me to specify the country, insert that id into the `getAll` request, and then performing the `getAll` query. Sometimes, this works, sometimes it does not. 

The times it does not work, it looks like the server is trying to submit the `getAll` request before checking if there are any `queryParams`. The times it does work, it loads the `queryParams` before `getAll`, so the tool ends up trying to load `/Countries/undefined/cities`, which obviously renders a 404.

My current "hack" is to click on the `Add Item` button (from my POST request) which loads my Country resources (since I have an optionSource coming from there as well), and generates the queryParams object. Then I close, the `Add Item` dialog to proceed with the getAll request 😛 

It seems like there just needs to be a check for queryParams before the getAll so that there is some consistency.

**Comment by jessemcdowell-AI** [comment]
I implemented required fields for the post and put pages, but it sounds like a good case for a required field in the query parameters.

Another hack you could try in the mean time is setting a default value for the query parameter. This would ensure there is always a value selected in the form, even before the options load.

**Comment by SonyaKaramchandani** [comment]
Thanks for the suggestion @jessemcdowell-AI! 

I thought of this as well, but it's still attempting to send the request through the getAll before attempting to check if there are query/path params, so even with a default value set, it's still not reciving value from queryParams that when sending the GET request to the API.

**Comment by SonyaKaramchandani** [comment]
So, I realised it's been a while since I've done a pull (woops- it's been a while since my last pull). That seemed to actually resolve it, and the expected behaviour is occurring consistently. 😃 Will reopen if I find otherwise but I think this one seems to be open and shut, thanks!!
