### ISSUE TITLE
DateTime Handling

### ISSUE THREAD

**Issue by ravola** [dsternlicht/RESTool#76]
My api returns datetime "2019-07-25T16:40:21.9440979+10:00" and time fields in these formats 00:24:05.8681579. Are there existing functions to handle datetime fields?

![image](https://user-images.githubusercontent.com/50979756/61852898-f0b71500-aefd-11e9-97d3-81883bec2530.png)

**Comment by dsternlicht** [comment]
@ravola nope, not at the moment, but it's a good idea (and should be easy) to support it.

**Comment by sktechinvento** [comment]
I have a related question.
If I were to add a datetime input in my project, what do I need to know? Is there any configuration-like changes to let the RESTool know it has another input type afterwards?

**Comment by dsternlicht** [comment]
@sktechinvento you'll need to add moment.js as a dependency to the project. Then, add a new display field type (https://github.com/dsternlicht/RESTool#display-field-types), and finally support the new type in both table view and cards view.

**Comment by dsternlicht** [comment]
@sktechinvento you may now convert the config file into a JS format, and use the `dataTransform` to change the date to the format you want!

Based on PR: https://github.com/dsternlicht/RESTool/pull/99
