### ISSUE TITLE
optionSource Change Request

### ISSUE THREAD

**Issue by ravola** [dsternlicht/RESTool#77]
@dsternlicht 
1. For a put request _optionSource_ - always takes an array in the displayPath to populate the 
   selectBox. Can this be made to populate as is from the datapath similar to display fields?
2. The url for the _optionSource_ cannot be parameterized unlike the getSelect.
    Ex: /api/Run/:id - doesn't work for _optionSource_ url

**Comment by dsternlicht** [comment]
@ravola good feedback. Added a TODO.

**Comment by dsternlicht** [comment]
Fixed in v2! :)
