### ISSUE TITLE
Error 0- Response with status: 0 for URL: null

### ISSUE THREAD

**Issue by sorvis** [dsternlicht/RESTool#8]
Hello,

Neat looking tool. I'm testing it out with one of our internal APIs, but I'm seeing a weird error message:

![image](https://user-images.githubusercontent.com/1037467/47172993-dc911800-d2da-11e8-974a-36091d8fff1d.png)

My page config looks like this:
```
{
      "name": "Applications",
      "id": "applications",
      "description": "List of applications",
      "methods":{
        "getAll":{
         "label": "Get Applications",
         "url": "INTERNAL URL",
         "dataPath": "result",
         "display":{
           "type": "table",
           "fields": [
             {
               "name": "name",
               "type": "text",
               "label": "Name"
             }
           ]
         }
        }
      }
    }
```

In the network tab of my browser I see it made a call out and got the following data similar to this:
```

{
	"code": 200,
	"path": "INTERNAL URL",
	"result": [{
			"active": true,
			"createdDate": "2018-09-26T08:06:05Z",
			"name": "Name 1",
			"updatedDate": "2018-09-26T08:06:05Z",
		}, {
			"active": true,
			"createdDate": "2018-10-04T06:41:36Z",
			"name": "Name 2",
			"updatedDate": "2018-10-04T06:41:36Z",
		}
	],
	"status": "ok",
	"timestamp": "2018-10-18T17:39:17Z",
	"verb": "GET"
}
```
Any suggestions of how I could further debug the issue?

**Comment by dsternlicht** [comment]
Hmmm... My first guess is the you want to remove the dataPath attribute from the getAll object. Did you try that?

**Comment by sorvis** [comment]
@dsternlicht figured it out today. Turns out it was a CORS issue. The API which is out of my control does not send the Access-Control-Allow-Origin header so my browser blocks it. Hmm, I wonder if there is some way for this app to skip around this or is that all the way in control of the browser? (I did find an extension that somewhat makes it work in Chrome)

**Comment by dsternlicht** [comment]
Nice catch.

Basically RESTool supports adding the relevant CORS headers from the client (take a look at the headers section in the configuration), but if the issue is coming from the server at the moment we don't have a solution for it.

**Comment by SalmanQuantNetwork** [comment]
where can I get debug information when my service doesnt return anything in Restool but works with postman...

**Comment by SalmanQuantNetwork** [comment]
I need this 	"requestHeaders": { Authorization: "Bearer XYXYXYXYYXYXYYXY" }

but it only works from the postman where the header is generated from the authorization token

**Comment by dsternlicht** [comment]
@SalmanQuantNetwork Can you get the Authorization header from postman, and just put it as a requestHeader in RESTool?
