### ISSUE TITLE
RESTool assets need to be installed at root of server

### ISSUE THREAD

**Issue by jessemcdowell-AI** [dsternlicht/RESTool#86]
We install RESTool in a sub-folder of our web application (ex: `http://host/product/config/`), but the index.html has references to the js/css/manifest file starting with a `/` such as `"/static/..."`. Because none of the content can be loaded, we're left with a blank page and a bunch of errors in the chrome console.

Release 2.0

**Comment by dsternlicht** [comment]
@jessemcdowell-AI Hmm... This could be fixed in the server level, but it's not optimal.

WDYT about adding all scripts and styles inline, meaning, inject everything to the html itself?

**Comment by jessemcdowell-AI** [comment]
I found a way to do with with a one-line changes to package.json. Take a look at https://github.com/dsternlicht/RESTool/pull/93

**Comment by dsternlicht** [comment]
Sweet!

Merging and closing.
