### ISSUE TITLE
PATCH method?

### ISSUE THREAD

**Issue by martov1** [dsternlicht/RESTool#9]
The docs dont seem to indicate support for the PATCH method, is this supported in some way?

Awesome software by the way!

**Comment by dsternlicht** [comment]
Hey @martov1 at the moment RESTool doesn't support PATCH requests, but it should be pretty simple to add it. Would you like to add this change and create pull request for it?

**Comment by dsternlicht** [comment]
Closing the issue for now.
@martov1 if it's still relevant for you, let me know.
