### ISSUE TITLE
how do I display fields from a nested JSON response ?

### ISSUE THREAD

**Issue by kpratihast** [dsternlicht/RESTool#96]
if my response to getAll method is as follows:
`{ [
    "fname": "abc",
     "cities" : {
           "tier1" : 1,
           "tier2" : 2,
            "name" : ["ca","lo"]
    }
]}
`
How do I display value of cities.tier2 in one of the header columns ?

**Comment by dsternlicht** [comment]
The `dataPath` should be `cities`, and the field name `tier2`.
