### ISSUE TITLE
Dots (.) in keys in json input mix up the data

### ISSUE THREAD

**Issue by Mythli** [dsternlicht/RESTool#97]
If I create a edit field like this:

```json
 {
  "name": "substitutions",
  "label": "Substitutions",
  "type": "object",
  "placeholder": ""
},
```

Given the following json string:

```json
{
  "http:": "https:",
  "webbee.chiemsee-sailingcenter.de":"chiemsee-sailingcenter.de"
}
```
the following will be posted to the server:

```json
{
  "http:": "https:",
  "webbee": {
    "chiemsee-sailingcenter": {
      "de": "chiemsee-sailingcenter.de"
    }
  }
}
```

I guess in some ways keys are parsed in the code.

**Comment by dsternlicht** [comment]
@Mythli That make sense, since we're parsing the properties to under the `dataPath` and using for the dot character for that. I guess we could add a configurable option for that rather than using dots automatically. Would you like to create a PR for that?

**Comment by Mythli** [comment]
I can look into it. My suggestion would be to make that the default or make it more obvious to users in the documentation.

**Comment by dsternlicht** [comment]
@Mythli 👍🏻
